import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ThreeLandingBackground from '@/pages/three/background_landing_page'
import TitleScreen from '@/components/TitleScreen'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div style={{height: "100%",width:"100%"}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{width: "100%", height:"100%"}}>
        <ThreeLandingBackground/>
        <TitleScreen firstTitle={"MOONIMIZE"} secondTitle={"Collectif"} marginTop={"0"} marginBottom={"0"} 
        colorFirstTitle={"Black"} colorSecondTitle={"#1ACAD5"} sizeSecondTitle={"170px"} sizeFirstTitle={"150px"}/>
      </main>
    </div>
  )
}
