import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import TitleScreen from '@/components/TitleScreen'
import {ThreeBackground} from '@/pages/three/BackgroundThreeJS'
import { CardProcess } from '@/components/CardProcess'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div style={{height: "100%",width:"100%"}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThreeBackground/>
      <div style={{width: "100%", position:"absolute", top:"36%"}}>
          <TitleScreen firstTitle={"MOONIMIZE"} secondTitle={"Collectif"} marginTop={"0"} marginBottom={"0"} 
          colorFirstTitle={"white"} colorSecondTitle={"#1ACAD5"} sizeSecondTitle={"140px"} sizeFirstTitle={"120px"} textAlign={"center"} paddingLeft={"0"}/>
      </div>
      <TitleScreen firstTitle={"NOS SERVICES"} secondTitle={"Ce que l'on sait faire"} marginTop={"0"} marginBottom={"0"} 
          colorFirstTitle={"black"} colorSecondTitle={"#1ACAD5"} sizeSecondTitle={"50px"} sizeFirstTitle={"60px"} textAlign={""} paddingLeft={"3%"}/>
      <div>
        <TitleScreen firstTitle={"PROCESS"} secondTitle={"comment ça marche ?"} marginTop={"10%"} marginBottom={"5%"} 
          colorFirstTitle={"black"} colorSecondTitle={"#1ACAD5"} sizeSecondTitle={"50px"} sizeFirstTitle={"60px"} textAlign={""} paddingLeft={"3%"}/>
        <CardProcess number={"001"} title={"Découverte"} description={"Nous nous entretenons avec vous afin de comprendre vos enjeux et vos besoins."}/>
        <CardProcess number={"002"} title={"Découverte"} description={"Nous nous entretenons avec vous afin de comprendre vos enjeux et vos besoins."}/>
        <CardProcess number={"003"} title={"Découverte"} description={"Nous nous entretenons avec vous afin de comprendre vos enjeux et vos besoins."}/>
        <CardProcess number={"004"} title={"Découverte"} description={"Nous nous entretenons avec vous afin de comprendre vos enjeux et vos besoins."}/>
        <CardProcess number={"005"} title={"Découverte"} description={"Nous nous entretenons avec vous afin de comprendre vos enjeux et vos besoins."}/>
        <CardProcess number={"006"} title={"Découverte"} description={"Nous nous entretenons avec vous afin de comprendre vos enjeux et vos besoins."}/>

      </div>
      

    </div>
  )
}
