// components/layout.js
import { Navbar } from './Navbar';
import Head from 'next/head'
import {ThreeBackground} from '@/components/three/BackgroundThreeJS'
import { Footer } from '@/components/Footer'
import styles from '@/styles/Layout.module.css';
import { BackgroundLine } from '@/components/BackgroundLine'
import AnimatedElement from "@/components/ServiceCard";
export default function Layout({ children }: any) {
  return (

    <div className={styles.layout}>
      <Head>
        <title>Moonimize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThreeBackground/>
      <BackgroundLine></BackgroundLine>
      <Navbar />
      <main style={{position: "relative" ,zIndex: 2, background:"#ffffff00", width:"100%"}}>{children}</main>
        <AnimatedElement />
      <Footer/>
    </div>
  )
}